Set Postfix compatibility level
osuosl-cookbooks/osl-postfix pull request #17
Opened 2020-10-29 00:34 UTC by detjensrobert

As requested in osuosl-cookbooks/osl-mailrelay#4.

2020-10-29 03:22 UTC, detjensrobert commented
![](https://github.trello.services/images/mini-trello-icon.png) [osl-mailrelay cookbook](https://trello.com/c/RcadQBNa/460-osl-mailrelay-cookbook)

2020-10-29 23:32 UTC, ramereth requested changes

2020-10-29 23:32 UTC, ramereth commented on attributes/default.rb
> +default['osl-postfix']['main']['compatibility_level'] = '2'
I believe we only need this on EL8, can you please make that change?

2020-10-30 23:00 UTC, ramereth approved these changes
Patch bump please.

2020-10-30 23:01 UTC, detjensrobert commented
!bump patch *

2020-10-30 23:01 UTC, merged

2020-10-30 23:01 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v1.2.3.  Have a nice day!