Add pfcat, pfdel scripts from cfengine
osuosl-cookbooks/osl-postfix pull request #18
Opened 2020-11-03 03:02 UTC by detjensrobert

As requested in osuosl-cookbooks/osl-mailrelay#4.

2020-11-03 20:20 UTC, ramereth requested changes

2020-11-03 20:20 UTC, ramereth commented on files/server/pfcat
> +fi
Can you please run `shellcheck` on this and fix the issues? Also please convert all tabs to spaces.

2020-11-03 20:20 UTC, ramereth commented on files/server/pfdel
> +	$email_addr = $ARGV[0];
Can you please convert all tabs to spaces and also convert this to two space indents like we do with ruby code?

2020-11-03 20:20 UTC, ramereth commented on test/integration/server/inspec/server_spec.rb
> +
I recommend you add the following tests as well (note: I'm not including the full path):
```
# should return 1
pfcat foo
# should return 255
pfdel foo@bar.com
```

2020-11-05 01:21 UTC, ramereth approved these changes
Please do a minor bump.

2020-11-05 01:26 UTC, detjensrobert commented
!bump minor ~

2020-11-05 01:26 UTC, merged

2020-11-05 01:27 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v1.3.0.  Have a nice day!