Enable selinux enforcing
osuosl-cookbooks/osl-postfix pull request #21
Opened 2021-01-15 19:50 UTC by zimmerry

2021-01-15 19:50 UTC, zimmerry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Enable SELinux Enforcing](https://trello.com/c/WlALaNKE/930-enable-selinux-enforcing)

2021-01-25 22:46 UTC, ramereth requested changes

2021-01-25 22:46 UTC, ramereth commented on recipes/default.rb
> +end
This is a cleaner way to do it. Please fix it globally.
```suggestion
include_recipe 'osl-selinux' if platform_family?('rhel')
```

2021-01-27 23:00 UTC, ramereth approved these changes
Please do a minor bump on `~`

2021-01-27 23:02 UTC, zimmerry commented
!bump minor ~

2021-01-27 23:02 UTC, merged

2021-01-27 23:02 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v1.5.0.  Have a nice day!